// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/63264e958ab542a0b4d09419
###
GET http://localhost:8080/contacts/63264e958ab542a0b4d0941a
###
GET http://localhost:8080/contacts/63264e958ab542a0b4d0941b
// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/63264e958ab542a0b4d09419
###
GET https://cse341-instructor.herokuapp.com/contacts/63264e958ab542a0b4d0941a
###
GET https://cse341-instructor.herokuapp.com/contacts/63264e958ab542a0b4d0941b

